[workspace]
members = ["libstellar"]


[package]
name = "Stellar"
version = "0.1.0"
edition = "2021"

[dependencies]
backtrace = "0.3.74"
clap = { version = "4.5.23", features = ["derive"] }
colored = "2.2.0"
crossterm = { default-features = false, version = "0.28.1" }
inquire = "0.7.5"
libstellar = { path = "./libstellar" }
log = "0.4.22"
parking_lot = "0.12.3"
regex = "1.11.1"
rich-logger = { version = "0.1.17" }
rustversion = "1.0.19"

[build-dependencies]
version_check = "0.9"

[features]
default = []
nightly = []
